services:
  - type: web
    name: bun
    env: docker
    repo: https://github.com/render-examples/bun-docker
    plan: starter
    autoDeploy: false
    buildCommand: bun run src/config/migrations.js    
    
